name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-level: '3.10'

      - name: Install Flet CLI
        run: |
          pip install flet

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK with Flet
        run: |
          flet build apk --no-interactive

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-calculator-apk
          path: build/apk/*.apk
